# Generated by Django 4.2.4 on 2023-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_userfollows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
