# Generated by Django 4.2.4 on 2023-09-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
